import { WordPressClient } from '../wordpress-client.js';
import { PostData, SEOData } from '../types.js';
import { MCPError } from '../utils/errors.js';
import { createCategoryTool } from './create-category.js';
import { createTagTool } from './create-tag.js';
import { embedImagesInContentTool } from './embed-images-in-content.js';
import { setSEOMetadataTool } from './set-seo-metadata.js';
import { verifyBlogStructureTool } from './verify-blog-structure.js';
import { uploadMediaTool } from './upload-media.js';

export interface CompleteBlogInput {
  topic?: string;
  doResearch?: boolean;
  depth?: 'basic' | 'comprehensive' | 'expert';
  targetAudience?: 'beginner' | 'intermediate' | 'expert';

  title?: string;
  content?: string;
  outline?: any;

  categories?: string[];
  tags?: string[];

  generateFeaturedImage?: boolean;
  generateSectionImages?: boolean;
  featuredImagePrompt?: string;

  localImages?: string[];

  seo?: SEOData;
  status?: 'draft' | 'publish' | 'pending';
  excerpt?: string;

  verifyBeforePublish?: boolean;
  dryRun?: boolean;
}

export const createCompleteBlogTool = async (params: {
  input: CompleteBlogInput;
  wpClient: WordPressClient
}) => {
  const { input, wpClient } = params;
  const results: any = { steps: [] };

  try {
    // 1. Verification (if dry run or requested)
    if (input.verifyBeforePublish || input.dryRun) {
      const verif = await verifyBlogStructureTool({
        blog: {
          title: input.title || '',
          content: input.content || '',
          seo: input.seo?.data,
          categories: input.categories,
          tags: input.tags
        }
      });
      results.verification = verif;
      results.steps.push('Blog structure verified');

      if (input.dryRun) return { success: true, dryRun: true, ...results };
    }

    // 2. Process Categories
    const categoryIds: number[] = [];
    if (input.categories) {
      for (const catName of input.categories) {
        const catRes = await createCategoryTool({ wpClient, category: { name: catName } });
        categoryIds.push(catRes.category.id);
      }
      results.steps.push(`${categoryIds.length} categories processed`);
    }

    // 3. Process Tags
    const tagIds: number[] = [];
    if (input.tags) {
      for (const tagName of input.tags) {
        const tagRes = await createTagTool({ wpClient, tag: { name: tagName } });
        tagIds.push(tagRes.tag.id);
      }
      results.steps.push(`${tagIds.length} tags processed`);
    }

    // 4. Process Content Images
    let processedContent = input.content || '';
    if (input.content) {
      const contentRes = await embedImagesInContentTool({
        content: input.content,
        wpClient,
        altPrefix: input.title
      });
      processedContent = contentRes.processedContent;
      results.steps.push('Content images processed');
    }

    // 5. Featured Image (Mocked if generated)
    let featuredMediaId: number | undefined;
    if (input.generateFeaturedImage) {
        // Here we would call an AI tool to generate an image
        // For now, we expect the featured image to be either provided or generated by AI assistant before this call
        results.steps.push('Featured image generation requested (handled separately)');
    }

    // 6. Create Post
    const postData: any = {
      title: input.title,
      content: processedContent,
      status: input.status || 'draft',
      categories: categoryIds,
      tags: tagIds,
      excerpt: input.excerpt
    };

    const postRes = await wpClient.createPost(postData);
    results.postId = postRes.id;
    results.link = postRes.link;
    results.steps.push('Post created in WordPress');

    // 7. Set SEO Metadata
    if (input.seo) {
      await setSEOMetadataTool({ wpClient, postId: postRes.id, seo: input.seo });
      results.steps.push('SEO metadata set');
    }

    return {
      success: true,
      ...results,
      message: `Complete blog post created successfully: ${postRes.link}`
    };

  } catch (err: any) {
    // Basic rollback could be added here (e.g., delete partial post if it was created)
    throw new MCPError('create_complete_blog_error', 'Failed to create complete blog post', {
      original: err?.message,
      partialResults: results
    });
  }
};
